### ISSUE TITLE
Version with keyboard code input.

### ISSUE THREAD

**Issue by Angelk90** [AudyOdi/react-native-android-pattern-lock-screen#2]
@AudyOdi :  First of all, I wanted to congratulate you on the module.
Could you do the same version, which instead of using the pattern-lock-screen allows you to enter the unlock code in a text field in order to access?
Like here: https://www.droid-life.com/wp-content/uploads/2013/03/lockscreen4.jpg

**Comment by AudyOdi** [comment]
@Angelk90 Hi! Thank you for the appreciation. I'm not really understand about the one that you suggest. Do you mean in order to unlock the screen, simply show custom keyboard to input unlock code, instead of using pattern? Clearer image about step by step or demo in Gif would be helpful!

**Comment by Angelk90** [comment]
@AudyOdi: See image: what you do is image 2, it would be interesting to do the same thing with image 3 and 1.

**Comment by Angelk90** [comment]
![](https://i.imgur.com/UpDVPcc.jpg)![](https://i.imgur.com/bm8g5WG.jpg)![](https://i.imgur.com/knQqqG5.jpg)![](https://i.imgur.com/zVpP8w7.jpg)![](https://i.imgur.com/uln2tTD.jpg)

**Comment by Angelk90** [comment]
@AudyOdi: I do not know, if now what I wanted to say is a little clearer. :)

**Comment by Angelk90** [comment]
@AudyOdi: Are there any news?
